### ISSUE TITLE
Xiaomi uses http for dns resolution to bypas hosts file blocking

### ISSUE THREAD

**Issue by mpsOxygen** [unknownFalleN/xiaomi-dns-blocklist#19]
Not really an issue, but good to know:

There is a little trick xiaomi can use to bypass this type of filtering, by using dns.io.mi.com (110.43.0.83 & 110.43.0.85) with a plain 'ol http GET request:

```json
Req:
  http://110.43.0.83/gslb?tver=2&id=1234567&dm=ots.io.mi.com&timestamp=13&sign=KmUuqqSuZiFCBY9hNLUr%2BewmH0RtVz6rvzwwrzFZjfk%3D
Resp:
  {
   "info":{
      "enable":1,
      "host_list":[
         {
            "ip":"120.92.96.155",
            "port":443
         },
         {
            "ip":"58.83.177.143",
            "port":443
         },
         {
            "ip":"183.84.5.209",
            "port":443
         }
      ]
   },
   "sign":"mR61hy8D05mEV6Owsawd9zV7Is49TXznwNkd4nqDjkU=",
   "timestamp":1624870689
   
```

From what I can tell Xiaomi hardcodes these IPs into some firmware in order to be complettly independent on local DNS settings.

**Comment by unknownFalleN** [comment]
Hi, do you have a valid `curl` request there. Currently I get for for `curl` req-url always only `{"message": "request not valid"}`

**Comment by mpsOxygen** [comment]
It does not work because the id= argument is not valid, I changed it because it was one of my device's id.
