### ISSUE TITLE
Couple of domains

### ISSUE THREAD

**Issue by pidus** [unknownFalleN/xiaomi-dns-blocklist#2]
Please add: 
us.api.micloud.xiaomi.net
us-api-micloud-xiaomi-net-5630734.us-west-2.elb.amazonaws.com

Thank you.

**Comment by pidus** [comment]
Also,

api-setting-intl-miui-com-59771552.ap-south-1.elb.amazonaws.com

**Comment by pidus** [comment]
Hmm, more: 

apidevicexiaominet-1824452031.ap-south-1.elb.amazonaws.com
findapi.micloud.xiaomi.net
pn.api.micloud.mi.com

**Comment by pidus** [comment]
findapi.micloud.xiaomi.net

**Comment by unknownFalleN** [comment]
Hey @pidus, 

thanks for the domains. Where did you find these?

**Comment by pidus** [comment]
I have EU ROM installed, and used personalDNSfilter app to see the connection log.
