### ISSUE TITLE
Remove candidates necessary for updating system apps and MIUI

### ISSUE THREAD

**Issue by shobhitagarwal1612** [unknownFalleN/xiaomi-dns-blocklist#24]
Needed for updating system apps:
`global.market.xiaomi.com`

Needed for MIUI Rom updates:
`update.intl.miui.com`

Please consider removing these from the blocklist.

**Comment by shobhitagarwal1612** [comment]
The first one is already mentioned in the Readme but is blocked. Maybe a script to check for whitelisted websites would prevent this in future?
Also, thanks for maintaining this really useful repo.

**Comment by unknownFalleN** [comment]
Added `update.intl.miui.com` to whitelist in README.  

I will probably create a second list where the whitelist entries are not in it and the blocklist will include all domains.
