### ISSUE TITLE
Blocking xiaomi kills battery!

### ISSUE THREAD

**Issue by onolox** [unknownFalleN/xiaomi-dns-blocklist#3]
In my Mi 9, MIUI 11, if I block xiaomi with this list, the phone starts to use much much more battery. Analysing with BBS I come to the conclusion that if some xiaomi services, like find my device can't call home, it starts to try reapeately to connect and turns itself in a battery killer. 
And we don't have anymore ways to kill those apps or it's wakelocks or alarms, then...

This is jus an alert to people, watch out your battery. Maybe someone can come with a solution.

**Comment by mikekuzak** [comment]
I heard about that .. some apps are retrying every second/minute or so.

**Comment by prudx** [comment]
Hey is this fixed? Also does this list just block unnecessary xiaomi dns or all? As I'd like to use this list but would still like to be able to update my phone etc. I couldn't find this info in the README. Thanks!

**Comment by unknownFalleN** [comment]
The Domain is removed  in 71ac8c2 commit. The list block a lot xiaomi domains. What of this makes sense and what of this does not make sense I can hardly decide for you ;) I'm not equipped with all the devices from xiaomi
