### ISSUE TITLE
subdomains from mi.com

### ISSUE THREAD

**Issue by alexladeira** [unknownFalleN/xiaomi-dns-blocklist#6]
Hi, I found this subdomains making hits on my pi-hole, can you add then to the list?
domain | hits
dlg.io.mi.com | 7733
ots.io.mi.com | 7698 
ot.io.mi.com | 6866
ott.io.mi.com | 1287

**Comment by jasirfayas** [comment]
On inspecting my pihole queries i saw these queries (which are not in the list) :-

- **cn.app.chat.xiaomi.net**
- **thm.market.intl.xiaomi.com**
- **sdkconfig.ad.india.xiaomi.com**
- **i.mi.com**
- **in.tv.global.mi.com**
- **g.galleryapi.micloud.xiaomi.net**
- **weatherapi.market.xiaomi.com**

I think the first 5 subdomains can be definitely blacklisted without consequences. The bottom 2 looks like they are related to mi cloud and weather app services (which are useless for me anyway).

**Comment by unknownFalleN** [comment]
Added the domains to the list ;)

**Comment by alexladeira** [comment]
> Added the domains to the list ;)

You added the list that @jasirfayas commented but not the ones that I originally opened the issue for. Am I right?

**Comment by unknownFalleN** [comment]
oh yes. Thanks for review the domains. I will fix it later today ;)

**Comment by unknownFalleN** [comment]
> dlg.io.mi.com | 7733
> ots.io.mi.com | 7698 
> ot.io.mi.com | 6866
> ott.io.mi.com | 1287

added first comment domains.

**Comment by alexladeira** [comment]
Great! Thank you!
