### ISSUE TITLE
Find my device longer works

### ISSUE THREAD

**Issue by DraTrav** [unknownFalleN/xiaomi-dns-blocklist#7]
the find device no longer works and will fail to find the device when connected to the network

**Comment by unknownFalleN** [comment]
with domains are used for find my device?

**Comment by DraTrav** [comment]
the domain us.find.api.micloud.xiaomi.net (global phone variant ) fixed my issue and allows find my device to work again however i'm willing to bet In.find.api.micloud.xiaomi.net is for the Indian variant  
and you cant login to your xiaomi account and disable find my device without
account.xiaomi.com
find.api.micloud.xiaomi.net 

so the remove list is 
us.find.api.micloud.xiaomi.net
account.xiaomi.com
find.api.micloud.xiaomi.net 
and maybe
In.find.api.micloud.xiaomi.net

**Comment by unknownFalleN** [comment]
Added documentation in README
