### ISSUE TITLE
System apps updater no longer works

### ISSUE THREAD

**Issue by DraTrav** [unknownFalleN/xiaomi-dns-blocklist#8]
the System apps updater on xiaomi phones fails to connect due to global.market.xiaomi.com being blocked

**Comment by unknownFalleN** [comment]
okay, it's thats the only one domain for systems updater? I will add a whitelist for the system app updater.

**Comment by DraTrav** [comment]
yes that is the only one required for the global system app updater unsure about other regional variants

**Comment by unknownFalleN** [comment]
Added documentation in README
