### ISSUE TITLE
Invalid Domains in Adlist

### ISSUE THREAD

**Issue by RaEyE** [unknownFalleN/xiaomi-dns-blocklist#9]
**Description**

> During the import of 'xiaomi.com.txt' via gravity update PiHole gives a info about invalid domains.
> Please see example

**PiHole version**

> Pi-hole v5.1.2
> Web Interface v5.1.1
> FTL v5.2

**Example**

> [i] Target: https://raw.githubusercontent.com/unknownFalleN/xiaomi-dns-blocklist/master/xiaomi.com.txt
>   [✓] Status: Retrieval successful
>   [i] Received 651 domains, 59 domains invalid!
>       Sample of invalid domains:
>       - *.a.market.xiaomi.com
>       - *.account.xiaomi.com
>       - *.ad.intl.xiaomi.com
>       - *.ad.xiaomi.com
>       - *.ai.xiaomi.com

**Comment by unknownFalleN** [comment]
The list xiaomi.com.txt is a automatically generated list with Sublert. I will describe it better in the Readme. This list only lists all domains that are found by certificate transparency. It can not be used directly in PiHole
